# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostty-config" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "05584dded034d85cf34aa14dbf0d24f6ad190ae47ea5aa35db04cffc7642a9e1"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f8b88495b1d8cc30f09730abc8927320c7cd32f21b0d13386ce55bdb32a95fb1"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "269c0d17273956af53c94f89852fa21a9facb743d3198656309e34e795064601"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2809b8522476f20349ed9a39d5d80b4d1f5cca0a266110b039bdb2ea13946bfb"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostty-config"
  desc "Configure Ghostty shaders and themes with live preview"
  homepage "https://github.com/victordantasdev/ghostty-config"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostty-config"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostty-config"]
    end
  end

  # No zap stanza required

end
