# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghostty-config" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f746b7ae20a5f451a5fda75788048bcc046657245758c9b0bfb8268a0a930751"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "90f27cdaf30dcb2e86b4b576c51712ee9a865d5660ec21695cad8d606d8787b5"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b20852f9bb4553d0f3741ceae11f61c984874e1cf11a0de2cb8524f32b96cb25"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e5cea7a07e983bd498502d7b04899d73315cf1b798cc1c6d487078a2487eb438"
      url "https://github.com/victordantasdev/ghostty-config/releases/download/v#{version}/ghostty-config_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ghostty-config"
  desc "Configure Ghostty shaders and themes with live preview"
  homepage "https://github.com/victordantasdev/ghostty-config"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ghostty-config"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghostty-config"]
    end
  end

  # No zap stanza required

end
